import type { NextApiRequest, NextApiResponse } from "next";

const empleadosMock: { [rfc: string]: any } = {
  ABCD123456XXX: {
    folio: "EMP001",
    clavePresupuestal: "CP-001-A",
    dependenciaEntidad: "Secretaría de Finanzas",
    dependenciaDireccion: "Dirección de Contabilidad",
    nombreTrabajador: "Juan Pérez García",
    cargo: "Administrador",
    puesto: "Director de Área",
    categoria: "A",
    nivel: "5",
    rfc: "ABCD123456XXX",
    curp: "PERJ850101HDFRGN01",
    horarioTrabajo: "8:00-16:00",
    movIncidencia: "Alta",
    sustituyeA: "",
    numerariaAlta: true,
    supernumerariaAlta: false,
    eventualAlta: false,
    percepcionSugeridaSueldoBase: "15000.00",
    percepcionSugeridaCompenExt: "5000.00",
    percepcionSugeridaProductividad: "2000.00",
    percepcionSugeridaPrestaciones: "3000.00",
    percepcionSugeridaNivelTab: "Nivel 5",
    percepcionSugeridaTotal: "25000.00",
    observaciones: "Empleado de nuevo ingreso, con alta en puesto directivo.",
    estado: "Aguascalientes",
    municipio: "Aguascalientes",
    codigoPostal: "20000",
    fechaIngreso: "2023-01-15",
    fechaMovimiento: "2023-01-15",
  },
  EFGH789012YYY: {
    folio: "EMP002",
    clavePresupuestal: "CP-002-B",
    dependenciaEntidad: "Secretaría de Educación Pública",
    dependenciaDireccion: "Departamento de Becas",
    nombreTrabajador: "María López Sánchez",
    cargo: "Analista",
    puesto: "Coordinador Junior",
    categoria: "B",
    nivel: "3",
    rfc: "EFGH789012YYY",
    curp: "LOMM900520MZRSTJ02",
    horarioTrabajo: "9:00-17:00",
    movIncidencia: "Cambio de Puesto",
    sustituyeA: "Carlos Ruiz",
    numerariaAlta: false,
    supernumerariaAlta: true,
    eventualAlta: false,
    percepcionSugeridaSueldoBase: "10000.00",
    percepcionSugeridaCompenExt: "3000.00",
    percepcionSugeridaProductividad: "1000.00",
    percepcionSugeridaPrestaciones: "2000.00",
    percepcionSugeridaNivelTab: "Nivel 3",
    percepcionSugeridaTotal: "16000.00",
    observaciones: "Promoción interna de asistente a coordinador.",
    estado: "Jalisco",
    municipio: "Guadalajara",
    codigoPostal: "44100",
    fechaIngreso: "2020-03-01",
    fechaMovimiento: "2023-06-01",
  },
  IJKL345678ZZZ: {
    folio: "EMP003",
    clavePresupuestal: "CP-003-C",
    dependenciaEntidad: "Secretaría de Salud",
    dependenciaDireccion: "Unidad Médica Familiar",
    nombreTrabajador: "Pedro Ramírez Gómez",
    cargo: "Auxiliar Administrativo",
    puesto: "Operativo",
    categoria: "C",
    nivel: "1",
    rfc: "IJKL345678ZZZ",
    curp: "RAGP781111HGRSSM03",
    horarioTrabajo: "Lunes a Viernes 8:00-17:00",
    movIncidencia: "Baja",
    sustituyeA: "",
    numerariaAlta: true,
    supernumerariaAlta: false,
    eventualAlta: false,
    percepcionSugeridaSueldoBase: "7000.00",
    percepcionSugeridaCompenExt: "1000.00",
    percepcionSugeridaProductividad: "500.00",
    percepcionSugeridaPrestaciones: "1000.00",
    percepcionSugeridaNivelTab: "Nivel 1",
    percepcionSugeridaTotal: "9500.00",
    observaciones: "Baja por renuncia voluntaria.",
    estado: "CiudadDeMexico",
    municipio: "Iztapalapa",
    codigoPostal: "09000", // Example CP
    fechaIngreso: "2022-09-01",
    fechaMovimiento: "2024-01-31",
  },
  MNOP901234AAA: {
    folio: "EMP004",
    clavePresupuestal: "CP-004-D",
    dependenciaEntidad: "Secretaría de Desarrollo Social",
    dependenciaDireccion: "Coordinación de Programas",
    nombreTrabajador: "Ana García Hernández",
    cargo: "Especialista en TI",
    puesto: "Analista Senior",
    categoria: "A",
    nivel: "4",
    rfc: "MNOP901234AAA",
    curp: "GAHA880310MDFRLJ04",
    horarioTrabajo: "Flexibilidad de horario",
    movIncidencia: "Reajuste de Sueldo",
    sustituyeA: "",
    numerariaAlta: true,
    supernumerariaAlta: false,
    eventualAlta: false,
    percepcionSugeridaSueldoBase: "18000.00",
    percepcionSugeridaCompenExt: "6000.00",
    percepcionSugeridaProductividad: "2500.00",
    percepcionSugeridaPrestaciones: "3500.00",
    percepcionSugeridaNivelTab: "Nivel 4",
    percepcionSugeridaTotal: "30000.00",
    observaciones: "Aumento de sueldo por desempeño sobresaliente.",
    estado: "NuevoLeon",
    municipio: "Monterrey",
    codigoPostal: "64000",
    fechaIngreso: "2019-07-20",
    fechaMovimiento: "2024-05-01",
  },
  QRST567890BBB: {
    folio: "EMP005",
    clavePresupuestal: "CP-005-E",
    dependenciaEntidad: "Secretaría de Cultura",
    dependenciaDireccion: "Departamento de Eventos",
    nombreTrabajador: "Luis Fernando Torres Vargas",
    cargo: "Gerente de Proyectos",
    puesto: "Gerente",
    categoria: "B",
    nivel: "6",
    rfc: "QRST567890BBB",
    curp: "TOVL920915HGDCRF05",
    horarioTrabajo: "9:00-17:00",
    movIncidencia: "Transferencia de Área",
    sustituyeA: "",
    numerariaAlta: true,
    supernumerariaAlta: false,
    eventualAlta: false,
    percepcionSugeridaSueldoBase: "20000.00",
    percepcionSugeridaCompenExt: "7000.00",
    percepcionSugeridaProductividad: "3000.00",
    percepcionSugeridaPrestaciones: "4000.00",
    percepcionSugeridaNivelTab: "Nivel 6",
    percepcionSugeridaTotal: "34000.00",
    observaciones: "Transferido de la Dirección de Arte a Eventos.",
    estado: "Puebla",
    municipio: "Puebla",
    codigoPostal: "72000",
    fechaIngreso: "2018-11-01",
    fechaMovimiento: "2024-02-10",
  },
};

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  const { rfc } = req.query;

  if (typeof rfc !== "string" || !rfc) {
    return res.status(400).json({ error: "RFC no proporcionado o inválido." });
  }

  const empleado = empleadosMock[rfc.toUpperCase()]; // Convertir a mayúsculas para coincidencia

  if (!empleado) {
    return res.status(404).json({ error: "Empleado no encontrado." });
  }

  res.status(200).json(empleado);
}